import type { ApiError, ApiResult, PaymentRequest, PaymentResponse } from "@/lib/types";

/**
 * The only place in this app that talks to the backend.
 *
 * Everything that leaves the browser goes through here so that authentication and
 * the headers the payments service requires are attached in exactly one place. A
 * direct `fetch` elsewhere sends a request without them.
 */

const API_BASE_URL = process.env.NEXT_PUBLIC_PAYMENTS_API_URL ?? "http://localhost:8080";

export const IDEMPOTENCY_KEY_HEADER = "Idempotency-Key";
export const REQUEST_ID_HEADER = "X-Request-Id";
export const ACTOR_HEADER = "X-Actor";

export interface RequestContext {
  /** Bearer token for the signed in customer. */
  authToken: string;
  /** Who the backend should record in the audit trail. */
  actor: string;
  /**
   * One key per logical payment attempt, reused on every retry of that attempt.
   * Generated by `newIdempotencyKey` and held by the caller across retries.
   */
  idempotencyKey?: string;
}

/**
 * Generates an idempotency key for a payment attempt.
 *
 * Hold on to the returned value for the lifetime of the attempt. Retrying with the
 * same key lets the payments service return the original outcome instead of
 * capturing the payment a second time.
 */
export function newIdempotencyKey(): string {
  return crypto.randomUUID();
}

function buildHeaders(context: RequestContext, method: string, path: string): Headers {
  const headers = new Headers({
    Accept: "application/json",
    Authorization: `Bearer ${context.authToken}`,
    [REQUEST_ID_HEADER]: crypto.randomUUID(),
    [ACTOR_HEADER]: context.actor,
  });

  if (method === "POST") {
    headers.set("Content-Type", "application/json");
  }

  // POST /payments is deduped server side on this header. The payments service
  // rejects the request outright when it is missing, because a payment capture
  // that cannot be retried safely is not something it will accept.
  if (method === "POST" && path === "/payments") {
    headers.set(IDEMPOTENCY_KEY_HEADER, context.idempotencyKey ?? newIdempotencyKey());
  }

  return headers;
}

async function readError(response: Response): Promise<ApiError> {
  try {
    const body: unknown = await response.json();
    if (
      typeof body === "object" &&
      body !== null &&
      "code" in body &&
      "message" in body &&
      typeof body.code === "string" &&
      typeof body.message === "string"
    ) {
      return { code: body.code, message: body.message };
    }
  } catch {
    // A non JSON error body is still a failure, it just carries no detail.
  }

  return { code: "unexpected_error", message: `Request failed with status ${response.status}` };
}

async function request<T>(
  path: string,
  method: "GET" | "POST",
  context: RequestContext,
  body?: unknown,
): Promise<ApiResult<T>> {
  let response: Response;

  try {
    response = await fetch(`${API_BASE_URL}${path}`, {
      method,
      headers: buildHeaders(context, method, path),
      body: body === undefined ? undefined : JSON.stringify(body),
      cache: "no-store",
    });
  } catch (thrown: unknown) {
    const message = thrown instanceof Error ? thrown.message : "network request failed";
    return { ok: false, error: { code: "network_error", message }, status: 0 };
  }

  if (!response.ok) {
    return { ok: false, error: await readError(response), status: response.status };
  }

  return { ok: true, data: (await response.json()) as T };
}

/** Captures a payment. Pass the same `idempotencyKey` when retrying an attempt. */
export function createPayment(
  payment: PaymentRequest,
  context: RequestContext,
): Promise<ApiResult<PaymentResponse>> {
  return request<PaymentResponse>("/payments", "POST", context, payment);
}

export function getPayment(
  paymentId: string,
  context: RequestContext,
): Promise<ApiResult<PaymentResponse>> {
  return request<PaymentResponse>(`/payments/${paymentId}`, "GET", context);
}
